name: Publish vue-cytoscape documentation

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      
      - name: Set Node.js 10.x
        uses: actions/setup-node@master
        with:
          version: 10.x

      - run: yarn install
      
      - run: ./deploy-docs.sh
