name: Publish vue-cytoscape documentation

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
          with:
            node-version: 10.x
      - run: ./deploy-docs.sh
